<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UWcS0SD' shared service.

return $this->privates['.service_locator.UWcS0SD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'category' => ['privates', '.errored..service_locator.UWcS0SD.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.UWcS0SD": it references class "App\\Entity\\Category" but no such service exists.'],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true],
], [
    'category' => 'App\\Entity\\Category',
    'paginator' => '?',
    'postRepository' => 'App\\Repository\\PostRepository',
]);
