<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.M3TzEER' shared service.

return $this->privates['.service_locator.M3TzEER'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'post' => ['privates', '.errored..service_locator.M3TzEER.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.M3TzEER": it references class "App\\Entity\\Post" but no such service exists.'],
    'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true],
], [
    'paginator' => '?',
    'post' => 'App\\Entity\\Post',
    'postRepository' => 'App\\Repository\\PostRepository',
]);
