<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.UAxc5K3', 'get_ServiceLocator_UAxc5K3Service.php', true],
    'App\\Controller\\CategoryController::posts' => ['privates', '.service_locator.UWcS0SD', 'get_ServiceLocator_UWcS0SDService.php', true],
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\PostController::delete' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController::edit' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController::index' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\PostController::show' => ['privates', '.service_locator.M3TzEER', 'get_ServiceLocator_M3TzEERService.php', true],
    'App\\Controller\\PostController::unapproved' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::unapproved' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.UAxc5K3', 'get_ServiceLocator_UAxc5K3Service.php', true],
    'App\\Controller\\CategoryController:posts' => ['privates', '.service_locator.UWcS0SD', 'get_ServiceLocator_UWcS0SDService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\PostController:delete' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController:edit' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController:index' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\PostController:show' => ['privates', '.service_locator.M3TzEER', 'get_ServiceLocator_M3TzEERService.php', true],
    'App\\Controller\\PostController:unapproved' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:unapproved' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
], [
    'App\\Controller\\CategoryController::delete' => '?',
    'App\\Controller\\CategoryController::edit' => '?',
    'App\\Controller\\CategoryController::index' => '?',
    'App\\Controller\\CategoryController::posts' => '?',
    'App\\Controller\\CategoryController::show' => '?',
    'App\\Controller\\PostController::delete' => '?',
    'App\\Controller\\PostController::edit' => '?',
    'App\\Controller\\PostController::index' => '?',
    'App\\Controller\\PostController::show' => '?',
    'App\\Controller\\PostController::unapproved' => '?',
    'App\\Controller\\UserController::delete' => '?',
    'App\\Controller\\UserController::edit' => '?',
    'App\\Controller\\UserController::show' => '?',
    'App\\Controller\\UserController::unapproved' => '?',
    'App\\Controller\\CategoryController:delete' => '?',
    'App\\Controller\\CategoryController:edit' => '?',
    'App\\Controller\\CategoryController:index' => '?',
    'App\\Controller\\CategoryController:posts' => '?',
    'App\\Controller\\CategoryController:show' => '?',
    'App\\Controller\\PostController:delete' => '?',
    'App\\Controller\\PostController:edit' => '?',
    'App\\Controller\\PostController:index' => '?',
    'App\\Controller\\PostController:show' => '?',
    'App\\Controller\\PostController:unapproved' => '?',
    'App\\Controller\\UserController:delete' => '?',
    'App\\Controller\\UserController:edit' => '?',
    'App\\Controller\\UserController:show' => '?',
    'App\\Controller\\UserController:unapproved' => '?',
]));
